language: bash
services: docker

env:
  global:
  - secure: MsFp7iaVDOyf4AhXs9MEXr54YM8J9Bg/Zt5bQRc3j01pQQzw/ZgFZWYgN03J6cd8+t7C8vMLwVRdy6BKwoDE1yzGXIMfjlkjeFNMDARST7jKZG78pr1aCY2fFttR/EXW4tGuZ7IxWceY2WZRVt9frx5nTq8FoaV4rlVG2iIZxWxPmzThIJIxCVjnVaEZvdKCN8MJ0DxwTXemIdputRPfqX935umVyDAJPOR3eH3GinTpIdcaZAPtX8j+eRG/N+uh8b1lpgYOJMHJA1q78Lu0/O4iSaJQdOANUBSyf1JERRnpuDAed1TGoJr2FQa3cgmDMFYAYa3CAw8jVWo9k92X23ilf9F4QLSjJyoBXbiZ2I0Smic8MMqKAmj6jtAfTVC34tsTeXIT5g28oQhcOvKOpBREpbQWybdtFkRfLIXFVxIu7IkGe0TVJQ6RNmvX+264F9HVg8NOP8Z/EdsWsuNaRDmty2MPM2moeDUkGDPLx/oCGrI3lwd+Mawkmj+F8fCXMLUr0oj+mPSB+T/ZtsMDHs4tr0dZtbMGbFBg2lutfBS5FloALjxMZ3tPahJGFJ8SYpQrZxv1BudC9v4Z0vqKeJzzfIJRfyKBIPFF3M78ZF9fDA7LunMw/iXsMOd24moj+TjcXTs56vjRkt6eBDa2Jb0tftW6azlKgBGRsum5eWk=
  - secure: g+Yn6hva0dwiq1yXz6Coy0B/35PvjQ9Hr2EB64jK/clB4/4EEeVEb6l18mXvF94BXRm93nk8yOpr5IXHkuSpM5t/hLfPCgFGoYM3P8QW0LBlG1e7Ps9IhVbeVR+2YqEIz/wsPxPqD5C4DmUufq8feEBjlu14WyfXxmxuO5U2faStua1kbr3tiVoyXnqX88MfXIQqnWx14pFDKOyNr/VVmCndV6S4V1rTOFGutD9zBnFwCz5scaLlHp/awW47KzYGBkuxiCaZk+9BV+FFaTQ4VlxfMtYcx/jUyu64UVQzIthmR6XUjXXv6uGOyCKatGil4NYKKiaqebng5xJz77nziMCFk4lJqFiHm6BBNegBMjAZw6Y26I7Bpd1KaQ+BATW3qgImMMozIaEyXlDsZ86PzUkaQ29vUFRyQ2aPfCs47W81/ZzInarOJXB1hCLgoX50USVHXyAmEmht+Nn+bW1/Qa4mCn69ykbrMJEqonguLKnOccIc+zcu3Z0FBDNdT8YSntRytYcRIUiKq3afp+jRVwbG8rAGKIodKBZ6IsAMHDa8KgoNcZm6Y1zZJDCmeASKix5LzGg6oU+KcsiWj/PDcz9cxmfhN2T66lsyH0kuXPyTwk6L8z/4yB2hNoVMCMpENuJkOF6RX94T8Orv4n0KxPx9g0xT8E3kQ44AJ4vxjSU=

  matrix:
    - ROOT_VERSION=6-14-04 VARIANT=debian PYTHON_VERSION=2.7
    # - ROOT_VERSION=6-14-04 VARIANT=debian PYTHON_VERSION=3.6
    # - ROOT_VERSION=6-14-04 VARIANT=debian PYTHON_VERSION=3.7

before_script:
  - cd "${VARIANT}/python_${PYTHON_VERSION}"
  - image="rootproject/root-${VARIANT}:${ROOT_VERSION}-python${PYTHON_VERSION}"

script:
  - docker build --build-arg ROOT_VERSION=${ROOT_VERSION} -t "$image" .

after_script:
  - docker images
